version: "3.3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:v5.8.1
    restart: always

    network_mode: host
    environment:
      TZ: 'Europe/Warsaw'
      INTERFACE: eth0
    volumes:
      - './etc-pihole:/etc/pihole'
      - './adlists.list:/etc/pihole/adlists.list'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    privileged: true
    cap_add:
      - NET_ADMIN

